### ISSUE TITLE
Recent changes break some decompressing

### ISSUE THREAD

**Issue by JimmXinu** [sidney/brotlidecpy#3]
I regret to report that something in the changes since a69c0b8165d751b8d0089fe302e14a85dfaf479e broke decompress for some cache entries.

I extracted the brotli compressed parts that failed from the cache files for ease of testing: [brotli-fails.zip](https://github.com/sidney/brotlidecpy/files/5913878/brotli-fails.zip)

They work fine with `brotli` or with `brotlidecpy` a69c0b8165d751b8d0089fe302e14a85dfaf479e

**Comment by sidney** [comment]
Cool, those files fail in the unit tests too, so I'll add them to `testdata` and get right on it.

**Comment by sidney** [comment]
I found the problem. I misinterpreted code in the javascript version I was translating to indicate that the first metadata block is a header for the entire file and contains the total expected length of the uncompressed data. I used that to create an output buffer of the correct size. That's wrong, each metadata block is independent and in those that contain data the length field is the length of the data in that block when uncompressed. The output buffer has to be dynamically extended whenever a new block that contains data is read. The test data sets I copied each had all data in one block. The examples that failed split the compressed data across multiple blocks. Testing a fix now.

**Comment by sidney** [comment]
@JimmXinu Please test branch issue-3 (currently commit f8aa06adf8) and let me know how it goes.

**Comment by JimmXinu** [comment]
Works for the cases I have on hand, but those are the same ones I gave you.  

I'll include that code in my testing today and let you know how it goes.

**Comment by sidney** [comment]
I just noticed that the test data contains multiple compressed versions of some of the test data, and my test code only used the first when there are multiple versions. When I corrected that I hit some test failures. Expect another round to test soon.

**Comment by JimmXinu** [comment]
Okay.  I haven't noticed any further problems in real world use.

**Comment by sidney** [comment]
One failure is a bug in `brotlipython`. Now that we know for sure that `brotlidecpy` is much faster than it, and we have `brotli` for reference results, I'll simply remove `brotlipython` from the tests. Another failure is the same problem that this issue addresses, handling cases in which the length field in the first metadata block is not the total uncompressed data length. That means that I don't have to add any of the test cases you supplied, as one of the ones I was not testing already covers it. And a final one is an edge case that I'll commit a fix for and ask you to try again.

**Comment by sidney** [comment]
@JimmXinu The issue-3 branch has been updated again. I merged in changes to the tests so it uses the test case files it had been missing, no longer uses brotlipython in the tests, and has changes that I made to have GitHub automatically run the tests in Python 2.7 and 3.9 whenever there is a push to GitHub. And it fixes the one new test failure that came out of the new cases. If this looks good to you I will merge it into master and release it as 1.0.3

**Comment by JimmXinu** [comment]
I've incorporated these changes and haven't seen any errors, nor heard reports of any.

**Comment by sidney** [comment]
I've merged the issue-3 branch to master and published release 1.0.3
Master right now is the same as what you got from the branch other than a release date in the changelog.

**Comment by JimmXinu** [comment]
Thanks!
